### ISSUE TITLE
User login validation

### ISSUE THREAD

**Issue by nicosammito** [nicosammitohamibot/JsHamibotAPI#1]

**Comment by nicosammito** [comment]
Will this work or do I need to change the body, because you are working with a different JSON format?

**Comment by nicosammito** [comment]
And is the validation endpoint correct?

**Comment by Th3Ph4nt0m** [comment]
This is an issue and there is no description provided. What should work? And which JSON format are you talking about?

**Comment by Taucher2003** [comment]
> This is an issue and there is no description provided. What should work? And which JSON format are you talking about?

He linked a Pull Request to this issue

**Comment by Th3Ph4nt0m** [comment]
Then this discussion should be continued there.
